// GENERATED by scripts/embed-clips.mjs — do not edit by hand.
export const CLIPS = [
  {
    "id": "cyberpunk",
    "name": "DeepSeek 赛博朋克片头",
    "ext": ".mp4",
    "bytes": 1856280,
    "sha256": "beabf5956e0b467e",
    "b64": 2475040
  }
]
